name: Lychee Config Check

on:
  pull_request:
    paths:
      - '.github/lychee.toml'
  push:
    paths:
      - '.github/lychee.toml'

permissions:
  contents: read

jobs:
  check-lychee-config:
    runs-on: ubuntu-latest
    name: Validate Lychee Config
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Lychee Config Checker
        id: lychee
        uses: lycheeverse/lychee-action@5c4ee84814c983aa7164eaee476f014e53ff3963 # v2.5.0
        with:
          args: "--verbose --config .github/lychee.toml --dump .github/lychee.toml"
          failIfEmpty: false
